FROM node:18-buster

# Create app directory
RUN apt update -y

WORKDIR /workdir
RUN npm i -g nodemon

COPY package*.json ./

RUN npm install --verbose


ENV PORT=31100
EXPOSE 31100
CMD [ "nodemon", "index.js" ]