version: '3'
services:

  myfileuploader:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /mnt/c/Users/vshanthi/Videos/Captures:/tmp/input-dir
      - /mnt/c/Users/vshanthi/Videos/Captures/zip:/tmp/zip/input-dir
    ports:
      - 31100:31100
    environment:
      - 'BACKEND_SERVICE_HOST=http://192.168.29.236:31100'
    container_name: myfileuploader
    # command: tail -f /dev/null
    restart: unless-stopped

  myfileuploaderdev:
    build:
      context: ./
      dockerfile: Dockerfile.develop
    volumes:
      - ./:/workdir
      - /workdir/node_modules
      # - /venkatesh_1tb_disk/file-upload-testing/upload-dir:/tmp/upload-dir
      - /mnt/c/Users/vshanthi/Videos/Captures:/tmp/input-dir
    ports:
      - 31101:31101
      - 31102:31102
    environment:
      - 'BACKEND_SERVICE_HOST=http://localhost:31102'
    container_name: myfileuploaderdev
    command: tail -f /dev/null
    # restart: unless-stopped
