FROM node:18-buster

# Create app directory
RUN apt update -y

WORKDIR /workdir
RUN npm i -g nodemon

COPY package*.json ./

RUN npm install --verbose


ENV PORT=31101
EXPOSE 31101
# CMD [ "nodemon", "index.js" ]