FROM node:18-buster

# Create app directory
RUN apt update -y

WORKDIR /workdir
RUN npm i -g pm2
RUN apt install sqlite3

COPY package*.json ./

RUN npm install --verbose
COPY . .
RUN cd client && npm install --verbose && cd ..


ENV PORT=31101
EXPOSE 31101
EXPOSE 31102
